---
title: स्प्राइट ड्रॉ (draw) करना
hero_image: images/banner.png
description: Scratch 3 में स्प्राइट को ड्रॉ करना
listed: false
ingredient: true
copyedit: true
steps:
  - 
    title: स्प्राइट ड्रॉ करना

