---
title: Desenarea personajelor
hero_image: images/banner.png
description: Desenarea personajelor în Scratch 3
listed: false
ingredient: true
copyedit: true
steps:
  - title: Desenarea personajelor

