---
title: Sprite ‌ಗಳನ್ನು ಚಿತ್ರಿಸುವುದು
hero_image: images/banner.png
description: Scratch 3 ರಲ್ಲಿ sprite ‌ಗಳನ್ನು ಎಳೆಯಿರಿ
listed: false
ingredient: true
copyedit: true
steps:
  - title: Sprite‌ ಗಳನ್ನು ಚಿತ್ರಿಸುವುದು

